// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using app.Context;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221207175341_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("app.DLL.Models.C8orApplied4Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("C8orId")
                        .HasColumnType("integer");

                    b.Property<int?>("Collabor8orId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Collabor8orId");

                    b.HasIndex("ProjectId");

                    b.ToTable("C8orsApplied4Projects");
                });

            modelBuilder.Entity("app.DLL.Models.C8orRequsted4Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("C8orId")
                        .HasColumnType("integer");

                    b.Property<int?>("Collabor8orId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Collabor8orId");

                    b.HasIndex("ProjectId");

                    b.ToTable("C8orsRequsted4Projects");
                });

            modelBuilder.Entity("app.DLL.Models.C8orSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("C8orId")
                        .HasColumnType("integer");

                    b.Property<int?>("Collabor8orId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Collabor8orId");

                    b.HasIndex("SkillId");

                    b.ToTable("C8orSkills");
                });

            modelBuilder.Entity("app.DLL.Models.Collabor8or", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Collabor8ors");
                });

            modelBuilder.Entity("app.DLL.Models.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("app.DLL.Models.PM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PMs");
                });

            modelBuilder.Entity("app.DLL.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contracts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ideas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PMId")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PMId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("app.DLL.Models.ProjectFounder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FounderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFounders");
                });

            modelBuilder.Entity("app.DLL.Models.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("app.DLL.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("app.DLL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("app.DLL.Models.C8orApplied4Project", b =>
                {
                    b.HasOne("app.DLL.Models.Collabor8or", "Collabor8or")
                        .WithMany("C8orApplied4Project")
                        .HasForeignKey("Collabor8orId");

                    b.HasOne("app.DLL.Models.Project", "Project")
                        .WithMany("C8orApplied4Project")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collabor8or");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("app.DLL.Models.C8orRequsted4Project", b =>
                {
                    b.HasOne("app.DLL.Models.Collabor8or", "Collabor8or")
                        .WithMany("C8orRequsted4Project")
                        .HasForeignKey("Collabor8orId");

                    b.HasOne("app.DLL.Models.Project", "Project")
                        .WithMany("C8orRequsted4Project")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collabor8or");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("app.DLL.Models.C8orSkill", b =>
                {
                    b.HasOne("app.DLL.Models.Collabor8or", "Collabor8or")
                        .WithMany("C8orSkill")
                        .HasForeignKey("Collabor8orId");

                    b.HasOne("app.DLL.Models.Skill", "Skill")
                        .WithMany("C8orSkill")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collabor8or");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("app.DLL.Models.Collabor8or", b =>
                {
                    b.HasOne("app.DLL.Models.User", "User")
                        .WithOne("Collabor8or")
                        .HasForeignKey("app.DLL.Models.Collabor8or", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.DLL.Models.Founder", b =>
                {
                    b.HasOne("app.DLL.Models.User", "User")
                        .WithOne("Founder")
                        .HasForeignKey("app.DLL.Models.Founder", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.DLL.Models.PM", b =>
                {
                    b.HasOne("app.DLL.Models.User", "User")
                        .WithOne("PM")
                        .HasForeignKey("app.DLL.Models.PM", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.DLL.Models.Project", b =>
                {
                    b.HasOne("app.DLL.Models.PM", "PM")
                        .WithMany("Project")
                        .HasForeignKey("PMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PM");
                });

            modelBuilder.Entity("app.DLL.Models.ProjectFounder", b =>
                {
                    b.HasOne("app.DLL.Models.Founder", "Founder")
                        .WithMany("ProjectFounder")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.DLL.Models.Project", "Project")
                        .WithMany("ProjectFounder")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Founder");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("app.DLL.Models.ProjectSkill", b =>
                {
                    b.HasOne("app.DLL.Models.Project", "Project")
                        .WithMany("ProjectSkill")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.DLL.Models.Skill", "Skill")
                        .WithMany("ProjectSkill")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("app.DLL.Models.Collabor8or", b =>
                {
                    b.Navigation("C8orApplied4Project");

                    b.Navigation("C8orRequsted4Project");

                    b.Navigation("C8orSkill");
                });

            modelBuilder.Entity("app.DLL.Models.Founder", b =>
                {
                    b.Navigation("ProjectFounder");
                });

            modelBuilder.Entity("app.DLL.Models.PM", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("app.DLL.Models.Project", b =>
                {
                    b.Navigation("C8orApplied4Project");

                    b.Navigation("C8orRequsted4Project");

                    b.Navigation("ProjectFounder");

                    b.Navigation("ProjectSkill");
                });

            modelBuilder.Entity("app.DLL.Models.Skill", b =>
                {
                    b.Navigation("C8orSkill");

                    b.Navigation("ProjectSkill");
                });

            modelBuilder.Entity("app.DLL.Models.User", b =>
                {
                    b.Navigation("Collabor8or");

                    b.Navigation("Founder");

                    b.Navigation("PM");
                });
#pragma warning restore 612, 618
        }
    }
}
