version: "1.1.3"
services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db
    db:
        image: "postgres"
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: "postgresUser"
            POSTGRES_PASSWORD: "postgresPW"
            POSTGRES_DB: "Collabor8"
            

